import test from 'node:test';
import assert from 'node:assert/strict';
import * as tracker from '../src/utils/unifiedProgressTracker.js';
import {grade1EnglishPath,recommendLevel,diagnosticBank} from '../src/data/grade1EnglishPath.js';
import {weeklySummary,validateStudentReport} from '../src/utils/reportGenerator.js';
import {workbookHtml} from '../src/utils/workbookGenerator.js';
const storage=new Map();globalThis.localStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)};globalThis.window={dispatchEvent:()=>{}};
const child=(name='Amina')=>tracker.saveProfile({displayName:name,grade:1,difficulty:'Medium',avatarId:'dilu_dolphin'});
function reset(){storage.clear()}

test('profiles stay isolated and enforce the four-child limit',()=>{reset();const a=child();tracker.recordActivityCompletion('ENG_G1_R1','OceanLearn',100,3,{id:'one'});const b=child('Ali');assert.equal(tracker.getProgress().stars,0);assert.equal(tracker.getSkillMasteryStatus('ENG_G1_R1'),'Not started');tracker.switchProfile(a.studentId);assert.equal(tracker.getProgress().stars,3);child('Hana');child('Isha');assert.throws(()=>child('Fifth'));assert.equal(tracker.getProfiles().length,4);assert.notEqual(a.studentId,b.studentId)});
test('grade and challenge matrix reaches levels 1–7',()=>{assert.equal(tracker.calculatedLevel(1,'Easy'),1);assert.equal(tracker.calculatedLevel(1,'Hard'),3);assert.equal(tracker.calculatedLevel(5,'Hard'),7)});
test('mastery thresholds and last-three-attempt averaging',()=>{reset();child();tracker.recordActivityCompletion('ENG_G1_R2','OceanLearn',20,1);assert.equal(tracker.getSkillMasteryStatus('ENG_G1_R2'),'Needs Practice');for(let i=0;i<3;i++)tracker.recordActivityCompletion('ENG_G1_R2','OceanPlay',90,3);assert.equal(tracker.getSkillMasteryStatus('ENG_G1_R2'),'Mastered');assert.equal(tracker.mastery(70),'Proficient');assert.equal(tracker.mastery(89),'Proficient');assert.equal(tracker.mastery(90),'Mastered')});
test('completion retries do not duplicate stars; connected journey advances',()=>{reset();child();const id='retry';tracker.recordActivityCompletion('ENG_G1_R1','OceanLearn',80,2,{id});tracker.recordActivityCompletion('ENG_G1_R1','OceanLearn',80,2,{id});assert.equal(tracker.getProgress().stars,2);assert.match(tracker.getConnectedNextStep('ENG_G1_R1').href,/play.atollingo.com\/connected/);tracker.recordActivityCompletion('ENG_G1_R1','OceanPlay',100,3);assert.equal(tracker.getConnectedNextStep('ENG_G1_R1').mode,'worksheet');tracker.recordActivityCompletion('ENG_G1_R1','Worksheets',100,3);assert.equal(tracker.getConnectedNextStep('ENG_G1_R1').mode,'lesson')});
test('invalid completion cannot alter learning results',()=>{reset();child();assert.throws(()=>tracker.recordActivityCompletion('bad','OceanLearn',100,3));assert.throws(()=>tracker.recordActivityCompletion('ENG_G1_R1','OceanLearn',NaN,3));assert.throws(()=>tracker.recordActivityCompletion('ENG_G1_R1','OceanLearn',101,3));assert.equal(tracker.getProgress().activities.length,0)});
test('legacy profile migrates without losing its name',()=>{reset();localStorage.setItem(tracker.PROFILE_KEY,JSON.stringify({name:'Laila',grade:2,difficulty:'Easy'}));assert.equal(tracker.getProfile().displayName,'Laila');assert.equal(tracker.getProfile().calculatedLevel,2)});
test('backup roundtrip, recovery copy, and invalid input are safe',()=>{reset();child();tracker.recordActivityCompletion('ENG_G1_R3','OceanLearn',80,2);const backup=tracker.exportProgressBackup();child('Other');tracker.importProgressBackup(backup);assert.equal(tracker.getProfiles().length,1);assert.equal(tracker.getProgress().stars,2);assert.ok(localStorage.getItem('atollingo_pre_import_backup'));const before=tracker.exportProgressBackup();assert.throws(()=>tracker.importProgressBackup('{invalid'));assert.equal(tracker.exportProgressBackup(),before);const bad=JSON.parse(backup);bad.family.progress[bad.family.activeId].skills.ENG_G1_R3.accuracy=400;assert.throws(()=>tracker.importProgressBackup(JSON.stringify(bad)))});
test('backup links cannot inject executable or unrelated destinations',()=>{assert.equal(tracker.safeActivityHref('javascript:alert(1)'),'/learn');assert.equal(tracker.safeActivityHref('https://evil.example'),'/learn');assert.equal(tracker.safeActivityHref('//evil.example'),'/learn');assert.equal(tracker.safeActivityHref('/learn?skill=ENG_G1_R1'),'/learn?skill=ENG_G1_R1')});
test('assignment completion stays with assigned child and skill',()=>{reset();const a=child(),b=child('Ali');tracker.writeLocal('atollingo_assignments',[{id:'task',studentId:a.studentId,skillId:'ENG_G1_R1',completed:false}]);tracker.recordActivityCompletion('ENG_G1_R1','OceanLearn',100,3);assert.equal(tracker.readLocal('atollingo_assignments',[])[0].completed,false);tracker.switchProfile(a.studentId);tracker.recordActivityCompletion('ENG_G1_R1','OceanLearn',100,3);assert.equal(tracker.readLocal('atollingo_assignments',[])[0].completed,true)});
test('weekly report excludes older and future work',()=>{const now=new Date('2026-09-09T12:00:00Z');const p={activities:[{at:'2026-09-08',seconds:120,starsEarned:2},{at:'2026-08-01',seconds:900,starsEarned:3},{at:'2027-01-01',seconds:900,starsEarned:3}]};assert.deepEqual(weeklySummary(p,now),{activities:1,minutes:2,stars:2})});
test('all six modules contain a complete lesson and valid assessment answers',()=>{assert.equal(grade1EnglishPath.length,6);for(const m of grade1EnglishPath){assert.ok(m.objective&&m.outcome&&m.home);assert.ok(m.explanation.length>=3&&m.explanation.length<=5);assert.equal(m.example.length,3);assert.ok(m.questions.length>=3&&m.questions.length<=5);for(const q of [m.guided,...m.questions,...m.game])assert.ok(q.answer>=0&&q.answer<q.options.length)}});
test('diagnostic boundaries and adaptive question bank',()=>{assert.equal(recommendLevel(2),1);assert.equal(recommendLevel(3),2);assert.equal(recommendLevel(4),2);assert.equal(recommendLevel(5),3);assert.ok(diagnosticBank.every(b=>b.length===5))});
test('printable workbook contains selected skills and separate answer key',()=>{const html=workbookHtml(['ENG_G1_R1','ENG_G1_R2']);assert.match(html,/Letter sounds/);assert.match(html,/Blending words/);assert.match(html,/Answer key/);assert.doesNotMatch(html,/Descriptive adjectives/);assert.doesNotMatch(workbookHtml(['ENG_G1_R1'],false),/Answer key/);assert.throws(()=>workbookHtml([]))});
test('teacher import rejects invalid skill evidence',()=>{assert.throws(()=>validateStudentReport({kind:'atollingo-student-report',student:{studentId:'x',displayName:'Learner'},progress:{activities:[],skills:{unknown:{accuracy:100}}}}))});

test('math objective scores are tracked independently and resume in MathLagoon',()=>{reset();child();const id=Object.keys(tracker.SKILLS).find(k=>k.startsWith('MATH_'));tracker.recordActivityCompletion(id,'MathLagoon',100,1,{id:'math-quiz-1'});assert.equal(tracker.getSkillMasteryStatus(id),'Mastered');assert.match(tracker.getConnectedNextStep(id).href,/lagoon.mathlagoon.com\/lessons\//);assert.equal(tracker.getProgress().stars,1);const backup=tracker.exportProgressBackup();assert.doesNotThrow(()=>tracker.validateBackup(backup))});
test('legacy completions are deduplicated without inventing mastery',()=>{reset();const p=child();tracker.recordExternalCompletion('OceanPlay',{id:'legacy-1',starsEarned:2},p.studentId);tracker.recordExternalCompletion('OceanPlay',{id:'legacy-1',starsEarned:2},p.studentId);assert.equal(tracker.getProgress().stars,2);assert.equal(tracker.getProgress().activities.length,1);assert.deepEqual(tracker.getProgress().skills,{});assert.doesNotThrow(()=>tracker.validateBackup(tracker.exportProgressBackup()))});
test('malformed learning drafts restart safely',()=>{reset();localStorage.setItem('bad-draft',JSON.stringify({step:99,answers:['wrong']}));const draft=tracker.readActivityDraft('bad-draft','lesson',5);assert.equal(draft.step,0);assert.deepEqual(draft.answers,[])});

test('student avatar choices persist without replacing existing family progress',()=>{storage.clear();const first=child();tracker.recordActivityCompletion('ENG_G1_R1','OceanLearn',100,3,{id:'avatar-check'});for(let i=1;i<=18;i++){tracker.saveProfile({...first,avatarId:'avatar-'+String(i).padStart(2,'0')});assert.equal(tracker.getProfile().avatarId,'avatar-'+String(i).padStart(2,'0'));assert.equal(tracker.getProfiles().length,1);assert.equal(tracker.getProgress().stars,3)}assert.throws(()=>tracker.saveProfile({...first,avatarId:'avatar-19'}));assert.equal(tracker.getProfile().avatarId,'avatar-18')});
