'use client';
import {useEffect,useState} from 'react';
import HubShell from '../components/HubShell';
import {ContinueLearningCard,DailyPlanChecklist,SkillPracticePills,TeacherAssignmentCard,SubjectGoalNav,apps} from '../components/DashboardCards';
import {getProfile,getProgress,saveProfile,readLocal,writeLocal,skillHref} from '../utils/unifiedProgressTracker';
export default function DashboardHub(){
 const [ready,setReady]=useState(false),[profile,setProfile]=useState(null),[progress,setProgress]=useState({skills:{},badges:[],stars:0}),[checked,setChecked]=useState([]),[error,setError]=useState(''),[assignments,setAssignments]=useState([]);
 useEffect(()=>{const refresh=()=>{try{const p=getProfile();setProfile(p);setProgress(getProgress());setChecked(readLocal(`atollingo_daily_${p?.studentId||'guest'}_${new Date().toLocaleDateString('en-CA')}`,[]));setAssignments(readLocal('atollingo_assignments',[]).filter(a=>a.studentId===p?.studentId&&!a.completed));setReady(true)}catch{setReady(true);setError('Your browser could not load saved learning. Allow site storage, then refresh.')}};refresh();window.addEventListener('atollingo-change',refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener('atollingo-change',refresh);window.removeEventListener('storage',refresh)}},[]);
 const weak=Object.entries(progress.skills||{}).filter(([,s])=>s.accuracy<70).map(([id,s])=>({id,...s}));
 const items=[{id:'lesson',title:'Discover a new English skill',detail:'Learn · 8 minutes',href:'/learn'},assignments[0]?{...assignments[0],detail:'Your assignment'}:{id:'practice',title:'Play with words',detail:'Practise · 5 minutes',href:'/learn?mode=game'},{id:'review',title:weak[0]?`Review ${weak[0].title||weak[0].id}`:'Read and review',detail:'Review · 3 minutes',href:weak[0]?skillHref(weak[0].id):'/learn?mode=worksheet'}];
 function start(e){e.preventDefault();const d=new FormData(e.currentTarget);try{saveProfile({displayName:String(d.get('name')).trim(),grade:Number(d.get('grade')),difficulty:d.get('difficulty'),avatarId:'dilu_dolphin'})}catch{setError('Your browser could not save your profile. Allow site storage and try again.')}}
 function toggle(id){try{const next=checked.includes(id)?checked.filter(x=>x!==id):[...checked,id];writeLocal(`atollingo_daily_${profile.studentId||'guest'}_${new Date().toLocaleDateString('en-CA')}`,next);setChecked(next)}catch{setError('Your checklist could not be saved.')}}
 return <HubShell>{error&&<p role="alert">{error}</p>}{!ready?<p role="status">Opening your learning lagoon…</p>:!profile?<section className="onboarding panel"><p className="eyebrow">WELCOME TO ATOLLINGO</p><h1>Your learning adventure starts here.</h1><p>Choose your starting point. You can change it any time.</p><form onSubmit={start}><label>Your name<input name="name" required maxLength={40} autoComplete="nickname"/></label><label>Your grade<select name="grade">{[1,2,3,4,5].map(g=><option key={g} value={g}>Grade {g}</option>)}</select></label><label>Your challenge<select name="difficulty" defaultValue="Medium">{['Easy','Medium','Hard'].map(d=><option key={d}>{d}</option>)}</select></label><button className="primary">Start learning →</button></form><p className="muted">Your profile stays in this browser. No email needed.</p></section>:<><ContinueLearningCard profile={profile} progress={progress}/><div className="dashboard-grid"><DailyPlanChecklist items={items} checked={checked} onToggle={toggle}/><section className="panel reward-panel"><p className="eyebrow">EVERY STEP COUNTS</p><h2>⭐ {progress.stars||0} stars</h2><div className="badges">{(progress.badges||[]).slice(-3).map((b,i)=><span key={b.id||i}>🏅 {b.title||b}</span>)}</div>{!progress.badges?.length&&<p>Your first badge is waiting. Complete a learning activity to begin.</p>}<a href="/diagnostic">Find my starting level →</a></section><SkillPracticePills skills={weak}/><TeacherAssignmentCard assignments={assignments}/></div><SubjectGoalNav grade={profile.grade}/></>}<section id="apps" className="apps-section"><h2>Explore all apps</h2><div className="app-links">{apps.map(([name,desc,href,icon])=><a key={name} href={href}><span aria-hidden="true">{icon}</span><b>{name}</b><small>{desc}</small></a>)}</div></section></HubShell>
}
